FROM arm32v7/node:18-alpine

WORKDIR /anylist

COPY package.json .
COPY index.js .

RUN npm install

COPY run-generic.sh .
RUN chmod a+x ./run-generic.sh

RUN --mount=type=secret,id=anylist_pass \
  cat /run/secrets/anylist_pass

CMD [ "PASSWORD=`cat /run/secrets/anylist_pass` ./run-generic.sh" ]
EXPOSE 9000
